name: Docker Image CI

on:
  push: ~
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      IMAGE_ID: ghcr.io/mojashi/twetter

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag twetter
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: Mojashi
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Push image
      if: startsWith(github.ref, 'refs/heads/')
      run: |
        docker tag twetter $IMAGE_ID:${GITHUB_REF////-}-latest
        docker push $IMAGE_ID:${GITHUB_REF////-}-latest